### ISSUE TITLE
Setup working environment (Visual Studio Code !!)

### ISSUE THREAD

**Issue by vsambor** [vsambor/Server-Client-Project#5]

**Comment by vsambor** [comment]
Please make sure that the project is running on your computer, after following the main [README](https://github.com/vsambor/Server-Client-Project/blob/master/README.md) (**This is a must!**).
So, before moving this task all of us should have the following checked:

- [ ] Visual Studio Code is installed
- [ ] Configuration added in user settings (see [README](https://github.com/vsambor/Server-Client-Project/blob/master/README.md), IDE part)
- [ ] All extensions mentioned in readme should be installed
- [ ] Make sure the ESlint and auto formatting works
- [ ] Mongo Db is installed
- [ ] Server and Client are running without problems on localhost (8080 - 8081)

**Comment by iliasnaamane** [comment]
Step 1,2,3,5 done for me

**Comment by paulbach83** [comment]
@vsambor it's ok for me =)

**Comment by BilalKoteich** [comment]
Done !
